from pathlib import Path

PREVIEW_FPS = 4
PREVIEW_INTERVAL = 1.0 / PREVIEW_FPS
PREVIEW_WIDTH = 180
PREVIEW_HEIGHT = 300
PREVIEW_WORKERS = 8
COMMAND_WORKERS = 12
DEVICE_CHECK_INTERVAL = 1000
BASE_DIR = Path(__file__).resolve().parent.parent
